---
title: "GooglePlayStore"
output:
  pdf_document: default
  html_document: default
---

```{r}
#Rating statistics bar chart Figure 4.2
ggplot(data,aes(x=data$Rating, fill = Type))+
  geom_bar()+
  theme_bw()+
  labs(y="Application Count",x="Store-Rating"
  )
```

```{r}

#Pie chart Content Rating Firgure 4.1
bp<- ggplot(data, aes(x="", y ="", fill = Content.Rating))+
  geom_bar(width = 1, stat = "identity")


pie <- bp + coord_polar("y", start=0)
pie

```

```{r}

#Category vs rating box plot Figure 4.3
cat.rating <- ggplot(data,aes(x=Category,y = Rating))+
  geom_boxplot(fill = "#EC7063")+
  theme_bw()+
  labs(y="Store-Rating",x="Category"
  )
cat.rating + theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r}

#Rating vs Price filterd by content rating figure 4.4
cat<- ggplot(data,aes(x=Reviews,y=Rating))+
  geom_point(fill = "#EC7063")+
  theme_bw()+
  labs(y="Store-Rating",x="Reviews"
  )
cat + geom_point(aes(colour = Content.Rating)) + theme(axis.text.x = element_text(angle=60,hjust=1))
```

```{r}

#Rating vs Size Figure 4.5
theme_set(theme_bw())  # pre-set the bw theme.
g <- ggplot(data, aes(x=Size, y=Rating))
g + geom_jitter(width = .5, size=1) + geom_point(fill = "#EC7063")+
  labs( 
    y="Store-Rating", 
    x="Size (Mb)" 
  )+ggtitle('Title')

```


```{r}
#Building the Linear Model
linearMod <- lm(Rating ~ Reviews+Size+Installs+Price, data=data)  # build the model
summary(linearMod)
```

```{r}

# Create Training and Test data -
set.seed(100)  # setting seed to reproduce results of random sampling
trainingRowIndex <- sample(1:nrow(data), 0.8*nrow(data))  # row indices for training data
trainingData <- data[trainingRowIndex, ]  # model training data
testData  <- data[-trainingRowIndex, ]

```

```{r}

# Building a predictor model
lmMod <- lm(Rating ~ Reviews+Size+Installs+Price, data=trainingData)  # build the model
RatingPred <- predict(lmMod, testData)  # predict rating
summary(lmMod)

```

```{r}

#Testing the model
actuals_preds <- data.frame(cbind(actual=testData$Rating, predicted=RatingPred))  # make actuals_predicteds dataframe.
correlation_accuracy <- cor(actuals_preds)  # 8%
```

```{r}
#displaying predicted vs actual ratings
head(actuals_preds)
```

```{r}
#Max and Min Predicted Ratings
max(actuals_preds$predicted)
min(actuals_preds$predicted)
```
